# Generated by Django 5.0.4 on 2024-05-06 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bayar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metode_pembayaran', models.CharField(max_length=50)),
                ('waktu_pembayaran', models.DateTimeField(auto_now_add=True)),
                ('pesanan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apiai.pesanan')),
            ],
        ),
    ]
