# Generated by Django 5.0.4 on 2024-05-06 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiai.itemmenu')),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_meja', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('item', models.ManyToManyField(through='apiai.ItemPesanan', to='apiai.itemmenu')),
            ],
        ),
        migrations.AddField(
            model_name='itempesanan',
            name='pesanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiai.pesanan'),
        ),
    ]
